name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Generate Git SHA
        id: vars
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build -t app-backend:${SHA_TAG} ./backend
          docker tag backend-app:${SHA_TAG} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend-app:${SHA_TAG}

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/app-backend:${SHA_TAG}

      - name: Build Frontend Image
        run: |
          docker build -t app-frontend:${SHA_TAG} ./frontend
          docker tag frontend-app:${SHA_TAG} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-app:${SHA_TAG}

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/app-frontend:${SHA_TAG}

      - name: Checkout GitOps Branch
        run: |
          git fetch origin gitops
          git checkout gitops

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|app-backend:.*|app-backend:${SHA_TAG}|g" k8s/backend-deployment.yaml
          sed -i "s|app-frontend:.*|app-frontend:${SHA_TAG}|g" k8s/frontend-deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add .
          git commit -m "updated image tag to ${SHA_TAG}" || echo "No changes"

          git push origin gitops